# Generated by Django 5.2.1 on 2025-05-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormattedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('candidate_name', models.CharField(default='Candidato', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CV Formateado',
                'verbose_name_plural': 'CVs Formateados',
            },
        ),
    ]
