# Generated by Django 5.2.1 on 2025-05-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formattedcv',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formattedcv',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
