"""
Django settings for cv_formatter project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde el archivo .env
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j9=j*v_ce*rg3-j2t&v0o@eaeujk3d1=9rgjvahf9#lfu(c4ip'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'formatter',    # Nuestra aplicación
    'corsheaders',  # Para CORS
    #'oauth2_provider',
    #'cognito_redux',
]

# Configuración de AWS Cognito
COGNITO = {
    'CLIENT_ID': os.getenv('COGNITO_CLIENT_ID'),
    'CLIENT_SECRET': os.getenv('COGNITO_CLIENT_SECRET'),
    'DISCOVERY_URL': os.getenv('COGNITO_DISCOVERY_URL'),
    'REDIRECT_URI': os.getenv('COGNITO_REDIRECT_URI'),
    'LOGOUT_URI': os.getenv('COGNITO_LOGOUT_URI'),
}

# DEBUG TEMPORAL - Eliminar después de probar
print("🔍 DEBUG - Verificando variables de entorno:")
print(f"BASE_DIR: {BASE_DIR}")
print(f"Archivo .env existe: {(BASE_DIR / '.env').exists()}")
print(f"COGNITO_CLIENT_ID: {os.getenv('COGNITO_CLIENT_ID')}")
print(f"COGNITO_CLIENT_SECRET: {os.getenv('COGNITO_CLIENT_SECRET')[:10]}..." if os.getenv('COGNITO_CLIENT_SECRET') else "None")
print(f"OPENAI_API_KEY: {os.getenv('OPENAI_API_KEY')[:10]}..." if os.getenv('OPENAI_API_KEY') else "None")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # Importante para las sesiones
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Añade tu middleware de autenticación personalizado aquí
    'formatter.middleware.AuthenticationMiddleware',  # Añade esta línea cuando hayas creado el middleware
]

# Configuración de sesiones (recomendado para mantener la sesión durante más tiempo)
SESSION_COOKIE_AGE = 86400  # Duración de la sesión en segundos (24 horas)
SESSION_SAVE_EVERY_REQUEST = True  # Refresca la sesión en cada petición

ROOT_URLCONF = 'cv_formatter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cv_formatter.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Configuración para archivos de medios
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'